// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYoy93Skh1-6a45uQLy5fKZOYKCqoCp4Y',
    appId: '1:381886891340:web:929a0197333e6bdb2efbe9',
    messagingSenderId: '381886891340',
    projectId: 'appqltaichinh',
    authDomain: 'appqltaichinh.firebaseapp.com',
    storageBucket: 'appqltaichinh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1myCQlrVazNC3wrXl1UXpSnkCwbGlrUM',
    appId: '1:381886891340:android:b847f352d9927c0b2efbe9',
    messagingSenderId: '381886891340',
    projectId: 'appqltaichinh',
    storageBucket: 'appqltaichinh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB4zJMTVCdHuGLoaYWG7Tv72omKCJn5lI',
    appId: '1:381886891340:ios:1cdc1898e51708dd2efbe9',
    messagingSenderId: '381886891340',
    projectId: 'appqltaichinh',
    storageBucket: 'appqltaichinh.firebasestorage.app',
    iosBundleId: 'com.example.appqltaichinh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB4zJMTVCdHuGLoaYWG7Tv72omKCJn5lI',
    appId: '1:381886891340:ios:1cdc1898e51708dd2efbe9',
    messagingSenderId: '381886891340',
    projectId: 'appqltaichinh',
    storageBucket: 'appqltaichinh.firebasestorage.app',
    iosBundleId: 'com.example.appqltaichinh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYoy93Skh1-6a45uQLy5fKZOYKCqoCp4Y',
    appId: '1:381886891340:web:1495d97cf7e2736f2efbe9',
    messagingSenderId: '381886891340',
    projectId: 'appqltaichinh',
    authDomain: 'appqltaichinh.firebaseapp.com',
    storageBucket: 'appqltaichinh.firebasestorage.app',
  );
}
